name: Windows Build

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    # runs-on: windows-latest
    runs-on: [self-hosted, Windows]

    # two days time out
    timeout-minutes: 2880
    
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.x'
    #- name: Install dotnet workload 
    #  run: dotnet workload install maui maccatalyst
    #- name: Check out submodules
    #  run: git submodule update --init --recursive
    - name: Build Emgu CV 32-bit native binary
      run: .\Build_Binary_x86.bat x86 nogpu vc no-openni no-doc no-package build
      working-directory: ${{ github.workspace }}\platforms\windows\
    - name: Clean up the 32-bit build
      run: .\git-clean.bat --keep_binary
      working-directory: ${{ github.workspace }}\miscellaneous
    - name: Build Emgu CV 64-bit native binary
      run: .\Build_Binary_x86.bat x86_64 nogpu vc no-openni no-doc package build nuget
      working-directory: ${{ github.workspace }}\platforms\windows\
    - uses: actions/upload-artifact@v4
      with:
        name: emgucv-windows-nsis-build-log
        path: ${{ github.workspace }}\build_x86_64\_CPack_Packages\win64\NSIS\*.log
    - uses: actions/upload-artifact@v4
      with:
        name: emgucv-windows-zip-package
        path: ${{ github.workspace }}\build_x86_64\*.zip
    - name: Run a test program
      run: dotnet run
      working-directory: ${{ github.workspace }}\Emgu.CV.Example\BuildInfo.Console\   
    #- name: Run Unit Test
    #  run: dotnet test --blame-crash
    #  working-directory: ${{ github.workspace }}\Emgu.CV.Test\Emgu.CV.Test.Netcore\   
    #- name: Clean up the non-gpu build
    #  run: .\git-clean.bat 
    #  working-directory: ${{ github.workspace }}\miscellaneous
    #- name: Build Emgu CV 64-bit native binary with GPU
    #  run: .\Build_Binary_x86.bat 64 gpu vc no-openni no-doc package build nuget
    #  working-directory: ${{ github.workspace }}\platforms\windows\
    #- uses: actions/upload-artifact@v2
    #  with:
    #    name: emgucv-windows-gpu-zip-package
    #    path: ${{ github.workspace }}\build_x64\*.zip
